config/routes.rb
OrbitalGlasses::Application.routes.draw do

  

  mount Spree::Core::Engine, :at => '/'

end

Spree::Core::Engine.routes.draw do
  

  namespace 'admin' do
    resources :notices
    resources :videos
    resources :stores
    resources :teams
    resources :contacts
  end

  resources :notices, only: [:index, :show]
  resources :videos, only: [:index, :show]
  resources :stores, only: [:index, :show]
  resources :teams, only: [:index, :show]
  
  resources :types, only: [:index]

  match 'contacts' => 'contacts#new', :as => 'contacts', :via => :get
  match 'contacts' => 'contacts#create', :as => 'contacts', :via => :post
end

app/models/spree/asset.rb
module Spree
  class Asset < ActiveRecord::Base
    belongs_to :viewable, polymorphic: true, touch: true
    acts_as_list scope: :viewable
    attr_accessible :cover
  end
end

app/models/spree/contact.rb
module Spree
	class Contact < ActiveRecord::Base
        validates :name, presence: true
        attr_accessible :name, :subject, :email, :body, :tipo_consulta, :estado
	end
end

app/models/spree/message.rb
module Spree
	class Message 
		include ActiveModel::Validations
		include ActiveModel::Conversion
		extend ActiveModel::Naming

		attr_accessor :name, :email, :subject, :body, :tipo_consulta

		validates :name, :email, :subject, :body, :tipo_consulta, :presence => true
		validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
	  
	  def initialize(attributes = {})
	  	attributes.each do |name, value|
	  		send("#{name}=", value)
	  	end
	  end

	  def persisted?
	  	false
	  end

	end
end

app/models/spree/mix.rb
module Spree
	class Mix < ActiveRecord::Base
	  validates :title, presence: true
    validates :description, presence: true
    validates :url, format: URI::regexp(%w(http https))
    validates :image, presence: true
    validates :dj_name, presence: true
    has_one :image, :as => :viewable, :order => :position, :dependent => :destroy

    accepts_nested_attributes_for :image
    attr_accessible :title, :description, :image_attributes, :url, :dj_name
	end
end

app/models/spree/notice.rb
module Spree
	class Notice < ActiveRecord::Base
	  validates :title, presence: true
    validates :description, presence: true
    validates :url, format: URI::regexp(%w(http https))
    validates :images, presence: true
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy

    accepts_nested_attributes_for :images, allow_destroy: true
    attr_accessible :title, :description, :images_attributes, :url
	end
end

app/models/spree/store.rb
module Spree
	class Store < ActiveRecord::Base
		validates :title, presence: true
    validates :description, presence: true
    validates :images, presence: true
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy

	  geocoded_by :address
	  after_validation :geocode, if: :address_changed?

    accepts_nested_attributes_for :images, allow_destroy: true
    attr_accessible :title, :description, :images_attributes, :address
	end
end

app/models/spree/team.rb
module Spree
    class Team < ActiveRecord::Base
    	validates :title, presence: true        
      validates :description, presence: true
	    validate :images, presence: true
	    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
      
      attr_accessible :title, :description, :images_attributes
	    accepts_nested_attributes_for :images, allow_destroy: true
	end
end

app/models/spree/video.rb
module Spree
  class Video < ActiveRecord::Base
  	validates :title, presence: true
    validates :description, presence: true
    validates :url, format: URI::regexp(%w(http https))
    validate :images, presence: true
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
 
    attr_accessible :title, :description, :url, :images_attributes, :_destroy
    accepts_nested_attributes_for :images, allow_destroy: true

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/spree/admin/contacts_controller.rb
module Spree
  module Admin
    class ContactsController < ResourceController
    end
  end
end

app/controllers/spree/admin/notices_controller.rb
module Spree
  module Admin
    class NoticesController < ResourceController
    end
  end
end

app/controllers/spree/admin/stores_controller.rb
module Spree
  module Admin
    class StoresController < ResourceController
    end
  end
end

app/controllers/spree/admin/teams_controller.rb
module Spree
  module Admin
    class TeamsController < ResourceController
    end
  end
end

app/controllers/spree/admin/videos_controller.rb
module Spree
  module Admin
    class VideosController < ResourceController
    end
  end
end

app/controllers/spree/contacts_controller.rb
module Spree
	class ContactsController < BaseController
		layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end
    def index
    	@contacts = Contact.all
    end
    def show
    	@contact = Contact.find(params[:id])
    end

		def new
	    @message = Message.new
	  end

	  def create
	    @message = Message.new(params[:message])
	    @contact = Contact.new(params[:message])
	    @contact.save
	    if @message.valid?
	      NotificationsMailer.new_message(@message).deliver
	      redirect_to(contacts_path, :notice => "Mensaje enviado correctamente.")
	    else
	      flash.now.alert = "Por favor, rellene todos los campos."
	      render :new
	    end
	  end

	end
end

app/controllers/spree/mixes_controller.rb
module Spree
  class MixesController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      @mixes = Mix.all

    end

    def show
      @mix = Mix.find(params[:id])
    end
  end
end

app/controllers/spree/notices_controller.rb
module Spree
  class NoticesController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      @notices = Notice.all

    end

    def show
      @notice = Notice.find(params[:id])
      @description = @notice.description.split(/\r\n/)

    end
  end
end

app/controllers/spree/stores_controller.rb
module Spree
  class StoresController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      @stores = Store.all

    end

    def show
      @store = Store.find(params[:id])
      @description = @store.description.split(/\r\n/)
    end
  end
end

app/controllers/spree/teams_controller.rb
module Spree
  class TeamsController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      @teams = Team.all

    end

    def show
      @team = Team.find(params[:id])
      @description = @team.description.split(/\r\n/)
    end
  end
end

app/controllers/spree/types_controller.rb
module Spree
  class TypesController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      if (params.has_key?(:types))
        @types = Spree::Taxon.find_by_permalink!(params[:types])
        @products = Spree::Product.in_taxon(@types)
        @taxons = Spree::Taxon.where('permalink like ?', "%#{params[:types]}%")
      else
        @products = Array.new
        @product_taxon = Hash.new

        @filter = Spree::Taxon.where('permalink like ?', "%#{params[:filter]}%")
        @filter.each do |filter|
          @product_taxon = ActiveRecord::Base.connection.select_all("SELECT * FROM spree_products_taxons WHERE taxon_id = #{filter.id}");
          unless @product_taxon.empty?
            @product_taxon.each do |tax|
              @lala = tax[:product_id]
              @products += Spree::Product.find(:all, :conditions => {:id => tax[:product_id]})
            end
          end
        end
        @taxons = Spree::Taxon.where('permalink like ?', "%#{params[:filter]}%")
      end
    end
  end
end

app/controllers/spree/videos_controller.rb
module Spree
  class VideosController < BaseController
    layout 'spree/layouts/spree_application'
    if defined?(Spree::Dash)
      helper 'spree/analytics'
    end

    def index
      @videos = Video.all

    end

    def show
      @video = Video.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/spree/admin/contacts/_form.html.haml
%fieldset
  = f.field_container :name do
    = f.label :name, t(:name)
    = f.text_field :name, :class => 'fullwidth title'
    = f.error_message_on :name

  = f.field_container :email do
    = f.label :email, t(:email)
    = f.text_field :email, :class => 'fullwidth title'
    = f.error_message_on :email

  = f.field_container :subject do
    = f.label :subject, 'subject'
    = f.text_field :subject, :class => 'fullwidth title'
    = f.error_message_on :subject
  
  = f.field_container :body do
    = f.label :body, 'body'
    = f.text_area :body, :class => 'fullwidth title'
    = f.error_message_on :body

  = f.field_container :tipo_consulta do
    = f.label :tipo_consulta, 'Tipo de consulta'
    = f.text_field :tipo_consulta, :class => 'fullwidth title'
    = f.error_message_on :tipo_consulta

  = f.field_container :estado do
    = f.label :estado, 'Estado'
    = f.select(:estado, options_for_select(['Nuevo','Revisado', 'Contestado', 'Finalizado'], :selected => @contact.estado) )

app/views/spree/admin/contacts/edit.html.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @contact }

= form_for [:admin, @contact], :method => :put, :html => { :multipart => true } do |f|
  = render 'form', f: f 
  = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/contacts/index.html.haml
.toolbar
  
%h1 Contact

%table.index
  %tr
    %th Name
    %th Subject
    %th Tipo de consulta
    %th Estado
    %th
  - @collection.each do |consulta|
    %tr
      %td= consulta.name
      %td= consulta.subject
      %td= consulta.tipo_consulta
      %td= consulta.estado
      %td.actions
        = link_to_edit consulta, :class => 'edit'
        &nbsp;
        = link_to_delete consulta

= paginate @collection.page(params[:page])

app/views/spree/admin/mixes/_form.html.haml
- @mix.build_image if @mix.image.nil?
%fieldset
  = f.field_container :title do
    = f.label :title, :title
    %span.required *
    %br
    = f.text_field :title, :class => 'fullwidth title'
    = f.error_message_on :title

  = f.field_container :description do
    %div
      You can add links to the description by using the following format:
      %br
        &lt;a href="http://the_url_to_link_to"&gt;The link's label&lt;/a&gt;
    = f.label :description, 'Description'
    %span.required *
    %br
    = f.text_area :description, :class => 'fullwidth title'
    = f.error_message_on :description
  
  = f.field_container :url do
    = f.label :url, 'Url'
    = f.text_field :url, :class => 'fullwidth title'
    = f.error_message_on :url

  = f.field_container :dj_name do
    = f.label :dj_name, 'Dj Name'
    = f.text_field :dj_name, :class => 'fullwidth title'
    = f.error_message_on :dj_name

  = f.fields_for :image, @mix.image do |fi|
    - if @mix.image.persisted?
      %div
        = image_tag @mix.image.attachment.url(:product), class: 'preview'
    = fi.label :attachment, 'Image'
    = fi.file_field 'attachment'

app/views/spree/admin/notices/_form.html.haml
- @notice.build_image if @notice.images.nil?
/ Agregamos el nombre de la seccion para poder identificarla y agregar imagenes
%fieldset.notice
  = f.field_container :title do
    = f.label :title, :title
    %span.required *
    %br
    = f.text_field :title, :class => 'fullwidth title'
    = f.error_message_on :title

  = f.field_container :description do
    %div
      You can add links to the description by using the following format:
      %br
        &lt;a href="http://the_url_to_link_to"&gt;The link's label&lt;/a&gt;
    = f.label :description, 'Description'
    %span.required *
    %br
    = f.text_area :description, :class => 'fullwidth title'
    = f.error_message_on :description
  
  = f.field_container :url do
    = f.label :url, 'Url'
    = f.text_field :url, :class => 'fullwidth title'
    = f.error_message_on :url

  = f.field_container :images do
    - unless @notice.images.nil?
      .row-fluid
        - @notice.images.each do |image|
          = f.fields_for :images, image do |ff|
            .span3
              .cover
                = ff.label :cover
                = ff.check_box :cover, :class => 'cover_select'
              .ph
                = image_tag(image.attachment.url(:small))
              .destroy
                = ff.label 'Destroy?'
                = ff.check_box :_destroy
    = f.fields_for :images, @notice.images.build do |fi|
      %div.images_field
        .row-fluid
          .span4
            = fi.label :attachment, 'Image'
            = fi.file_field 'attachment'
    
  .row-fluid            
    = f.button 'Add new image', :class => 'add-image'

app/views/spree/admin/notices/edit.html.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @notice }

= form_for [:admin, @notice], :method => :put, :html => { :multipart => true } do |f|
  = render 'form', f: f 
  = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/notices/index.html.haml
.toolbar
  %ul.actions
    %li#new_new_link
      = button_link_to 'New Notice', new_object_url, { :remote => true, :icon => 'add', :id => 'admin_new_notice' }
  %br.clear

%h1 Notices

#new_notice

%table.index#listing_notice
  %tr
    %th Title
    %th Link
    %th Image
    %th
  - @collection.each do |notice|
    %tr
      %td= notice.title
      %td= notice.url
      %td
        - unless notice.images.empty?
          = image_tag(notice.images.first.attachment.url(:small))
      %td.actions
        = link_to_edit notice, :class => 'edit'
        &nbsp;
        = link_to_delete notice

= paginate @collection.page(params[:page])

app/views/spree/admin/notices/new.html.haml
= render :partial => 'spree/shared/error_messages', :locals => { :target => @notice }

= form_for [:admin, @notice], html: {multipart: true} do |f|
  = render 'form', f: f 
  = render :partial => 'spree/admin/shared/new_resource_links'

app/views/spree/admin/notices/new.js.erb
$("#new_notice").html('<%= escape_javascript(render :template => "spree/admin/notices/new", :formats => [:html], :handlers => [:haml]) %>');
$("#admin_new_notice").parent().hide();

app/views/spree/admin/stores/_form.html.haml
- @store.build_image if @store.images.nil?
%fieldset.store
  = f.field_container :title do
    = f.label :title, :title
    %span.required *
    %br
    = f.text_field :title, :class => 'fullwidth title'
    = f.error_message_on :title

  = f.field_container :description do
    %div
      You can add links to the description by using the following format:
      %br
        &lt;a href="http://the_url_to_link_to"&gt;The link's label&lt;/a&gt;
    = f.label :description, 'Description'
    %span.required *
    %br
    = f.text_area :description, :class => 'fullwidth title'
    = f.error_message_on :description

  = f.field_container :address do
    = f.label :address, 'Address'
    %span.required *
    %br
    %div
      En base a esta dirección se mostrará el mapa del store, debe contener la calle, la altura, el barrio y la ciudad, por ejemplo:</br>Pringles 1395, Palermo, Buenos Aires, Argentina.
    = f.text_field :address, :class => 'fullwidth title'

  = f.field_container :images do
    - unless @store.images.nil?
      .row-fluid
        - @store.images.each do |image|
          = f.fields_for :images, image do |ff|
            .span3
              .cover
                = ff.label :cover
                = ff.check_box :cover, :class => 'cover_select'
              .ph
                = image_tag(image.attachment.url(:small))
              .destroy
                = ff.label 'Destroy?'
                = ff.check_box :_destroy
    = f.fields_for :images, @store.images.build do |fi|
      %div.images_field
        .row-fluid
          .span4
            = fi.label :attachment, 'Image'
            = fi.file_field 'attachment'
            =# fi.label :cover
            = #fi.check_box :cover, :class => 'cover_select'

  .row-fluid            
    = f.button 'Add new image', :class => 'add-image'

app/views/spree/admin/stores/edit.html.haml
=# render :partial => 'spree/shared/error_messages', :stores => { :target => @store }

= form_for [:admin, @store], :method => :put, :html => { :multipart => true } do |f|
  = render 'form', f: f 
  = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/stores/index.html.haml
.toolbar
  %ul.actions
    %li#new_store_link
      = button_link_to 'New Store', new_object_url, { :remote => true, :icon => 'add', :id => 'admin_new_store' }
  %br.clear

%h1 Store

#new_store

%table.index#listing_local
  %tr
    %th Title
    %th Description
    %th Image
    %th Actions
  - @collection.each do |store|
    %tr
      %td= store.title
      %td= store.description.truncate(40)
      %td
        - unless store.images.empty?
          = image_tag(store.images.first.attachment.url(:small)) if store.images
      %td.actions
        = link_to_edit store, :class => 'edit'
        &nbsp;
        = link_to_delete store

= paginate @collection.page(params[:page])

app/views/spree/admin/stores/new.html.haml
=# render :partial => 'spree/shared/error_messages', :stores => { :target => @store }

= form_for [:admin, @store], html: {multipart: true} do |f|
  = render 'form', f: f 
  = render :partial => 'spree/admin/shared/new_resource_links'

app/views/spree/admin/stores/new.js.erb
$("#new_store").html('<%= escape_javascript(render :template => "spree/admin/stores/new", :formats => [:html], :handlers => [:haml]) %>');
$("#admin_new_store").parent().hide();
addImages();

app/views/spree/home/index.html.haml
#contentinside
	.row-fluid
		%ul.bxslider
			%li.item
				= image_tag("01.jpg")
			%li.item
				= image_tag("02.jpg")
			%li.item
				= image_tag("03.jpg")
			%li.item
				= image_tag("04.jpg")
			%li.item
				= image_tag("05.jpg")
	.row-fluid
		.span4
			.row-fluid
				= link_to(types_path(:types => 'Sunglasses', :gender => 'hombre'), :class => 'box midbox') do
					.ph
						= image_tag("solhombre.jpg")
					.over
						%h1 SUNGLASSES MEN
						%p show collection
			.row-fluid
				= link_to('products/zeta-1-4', :class => 'box midbox') do
					.ph
						= image_tag("zetaseries.jpg")
					.over
						%h1 ZETA SERIES
						%p show product
			.row-fluid
				= link_to(teams_path, :class => 'box midbox') do
					.ph
						= image_tag("team.jpg")
					.over
						%h1 TEAM
						%p show riders
		.span4
			.row-fluid
				= link_to(types_path(:types => 'Watches'), :class => 'box midbox') do
					.ph
						= image_tag("watches.jpg")
					.over
						%h1 WATCHES
						%p show collection
			.row-fluid
				= link_to(notices_path, :class => 'box midbox') do
					.ph
						= image_tag("noticias.jpg")
					.over
						%h1 NEWS
						%p show news
			.row-fluid
				= link_to(types_path(:types => 'Prescription', :gender => 'hombre'), :class => 'box midbox') do
					.ph
						= image_tag("large01.jpg")
					.over
						%h1 PRESCRIPTION MEN
						%p show collection
		.span4
			.row-fluid
				= link_to(types_path(:types => 'Sunglasses', :gender => 'mujer'), :class => 'box midbox') do
					.ph
						= image_tag("solmujer.jpg")
					.over
						%h1 SUNGLASSES WOMEN
						%p show collection
			.row-fluid
				= link_to(types_path(:types => 'Prescription', :gender => 'mujer'), :class => 'box midbox') do
					.ph
						= image_tag("recetamujer.jpg")
					.over
						%h1 PRESCRIPTION WOMEN
						%p show collection
			.row-fluid
				= link_to(stores_path, :class => 'box midbox') do
					.ph
						= image_tag("stores.jpg")
					.over
						%h1 STORES
						%p show stores

app/views/spree/layouts/spree_application.html.haml
!!! Strict
%html
	%head
		%title Orbital
		= stylesheet_link_tag "store/all", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyAoAqRFSg4SPOGlkeJumobsLgCYKIAAEM0&sensor=false"  
	%body{controller: controller_name, action: action_name, :onload => "initialize()"}
		.container
			= render 'spree/shared/navigation'
			.row-fluid
				- flash.each do |name, msg|
					- if msg.is_a?(String) 
						%div{:class => "alert alert-#{name == :alert ? "error" : "success"}"}
						%a.close{"data-dismiss" => "alert"}
						= content_tag :div, msg, :id => "flash_#{name}"
			= yield
		.container
			#footer
				.row-fluid
					.span4
						= link_to('Sunglasses', types_path(:types => 'Sunglasses'))
						= link_to('Prescription', types_path(:types => 'Prescription'))
						= link_to('Watches', types_path(:types => 'Watches'))
						= link_to('Snowgoogles', types_path(:types => 'Snowgoogles'))
						.hr
					.span4
						= link_to('Home', root_path)
						= link_to('Team', teams_path)
						= link_to('Stores', stores_path)
						= link_to('News', notices_path)
						.hr
						.newsletter
					.span4
						= link_to('Contact', contacts_path)
						= link_to('About Orbital', )
						.hr
						%a.fb(href="https://www.facebook.com/orbitaleyewear")
						%a.tw(href="https://twitter.com/Orbitalvirtual")
				.row-fluid(style="margin-top:30px;")
					%a#gototop.top
				.row-fluid
					.footerinside
						%p 2013 ORBITAL. Todos los derechos reservados.
						%a.nuevediez 0910
				.row-fluid

app/views/spree/notices/index.html.haml
.row-fluid.whitebg
  - @notices.each do |notice|
    .span3
      = link_to(notice, class: 'box smallbox') do
        - unless notice.images.empty?
          .ph{:style => "background-image: url(#{notice.images.first.attachment.url(:large)})"} 
          .over
            %h1= notice.title
            %p ver detalle

app/views/spree/notices/show.html.haml
%p#notice
	= notice
.row-fluid
	.span12.seriesnav
		%h1
			= @notice.title
		= link_to 'Volver', notices_path, class:'back'
.row-fluid
	%ul.bxslider
		- @notice.images.each do |image|
			%li.item
				= image_tag(image.attachment.url(:original))
.row-fluid.fullbox
	%p
		- @description.each do |description|
			= description
			%br
.row-fluid.fullbox
	%P
		= link_to @notice.url, @notice.url

app/views/spree/products/index.html.haml
.row-fluid
  .span12.seriesnav
    %a Sol
    %a Hombre
    %a Vintage Series
.row-fluid
  .span12.seriesdesc
    %p
      Íconos del mundo de las gafas de los años 50’s y 60’s representados en la
      actualidad utilizando los mismos materiales de aquella época, colores, estilo, y
      respetando una escencia fresca y colorida, adaprando el estilo a nuestros tiempos.
.row-fluid
  - @products.each do |product|
    .span3
      = link_to(product, class: 'box smallbox') do
        .ph
          = large_image(product, :itemprop => "image")
        .over
          %h1= product.name
          %p ver detalle

app/views/spree/products/show.html.haml
%p#notice
	= notice
.row-fluid
	.span12.seriesnav
		- @taxons = @product.taxons.first.permalink.split('/')
		- @taxons.each do |tax|
			= link_to(types_path(:types => tax)) do
				= tax
			- @taxon = tax
		= link_to('Volver al catálogo', types_path, class: 'backtocat')
.row-fluid.prod
	.span6.prodphoto
		- @product.images.each do |image|
			= link_to image_tag(image.attachment.url(:large)), image.attachment.url(:original), class: 'cloud-zoom', rel:'adjustX: 0, adjustY:0'
		- @variants = @product.variants.active
		- @variants.each do |variant|
			- variant.images.each do |image|
				= link_to image_tag(image.attachment.url(:large)), image.attachment.url(:original), class: 'cloud-zoom', rel:'adjustX: 0, adjustY:0'
	.span6.proddesc
		%h1 #{@product.name}
		=raw product_description(@product).gsub("\n","<br/>") rescue t(:product_has_no_description)
		.formbox
			= form_for :order, url: populate_orders_url do |f|
				.formitem
					.span3
						%label Cantidad:
					.span2
						= number_field_tag (@product.has_variants? ? :quantity : "variants[#{@product.master.id}]"), 1, :class => 'title', :in => 1..100
					.span7
						.addtocart
							%input.button(type="submit" value="agregar al carrito")				
.row-fluid
	.span12.variants
		.variant
			%p variantes
		- i = 1
		- @product.images.each do |image|
			=# link_to image_tag(image.attachment.url(:large)), image.attachment.url(:original), class: 'cloud-zoom', rel:'adjustX: 0, adjustY:0'
			.variant
				= link_to('', :data => {:toggle => 'tooltip', :placement => 'top', :title => image.alt}, :class => i) do
					.ph
						= image_tag(image.attachment.url(:small))
				- i+=1
		-# @variants = @product.variants.active
		- @variants.each do |variant|
			- variant.images.each do |image|
				.variant
					= link_to('', :data => {:toggle => 'tooltip', :placement => 'top', :title => image.alt }, :class => i) do
						.ph
							= image_tag(image.attachment.url(:small))
					- i+=1
.row-fluid
	.span12.title
		%p Otros modelos de esta coleccion
- @types = Spree::Taxon.find_by_name!(@taxons[0])
- @related = Spree::Product.in_taxon(@types)
.row-fluid.related
	- @related.each do |prod_rel|
		- unless prod_rel.deleted_at!=nil
			.span2
				= link_to(product_path(prod_rel), class: 'box minibox') do
					.ph			
						= image_tag(prod_rel.images.first.attachment.url(:large))
					.over
						%h1 #{prod_rel.name}
						%p ver detalle

:javascript
	producttype = $('.seriesnav').find('a').eq(0).text().replace(/^\s+|\s+$/g,'');
	if (producttype == 'watches'){
		$('.wrap').addClass('watchwrap').removeClass('smallbox');
		$('.variant').css('height', '98px');
		$('.variants p').css('margin-top', '18px');
	}

app/views/spree/stores/index.html.haml
.row-fluid.whitebg
  - @stores.each do |store|
    .span3
      = link_to(store, class: 'box smallbox') do
        - unless store.images.empty?
          .ph{:style => "background-image: url(#{store.images.first.attachment.url(:large)})"} 
          .over
            %h1= store.title
            %p ver detalle

app/views/spree/stores/show.html.haml
%p#notice
	= notice
.row-fluid
	.span12.seriesnav
		%h1
			= @store.title
		= link_to 'Volver', stores_path, class:'back'
.row-fluid
	%ul.bxslider
		- @store.images.each do |image|
			%li.item
				= image_tag(image.attachment.url(:original))
.row-fluid.fullbox
	%p
		- @description.each do |description|
			= description
			%br
.row-fluid
	#map_canvas

:javascript
	myCenter = new google.maps.LatLng(#{@store.latitude}, #{@store.longitude});
	function initialize() {

		var mapOptions = {
			center: myCenter,
			zoom: 16,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		var map = new google.maps.Map(document.getElementById("map_canvas"),
		mapOptions);
		var marker=new google.maps.Marker({
			position:myCenter,
		});

		marker.setMap(map);

	}